# Finding the closest pair of points

In [1]:
import numpy as np

## Merge Sort

In [225]:
X = np.random.rand(64,2)

In [229]:
def sort_2(array):
    if array[0][0] > array[1][0]:
        return np.array([array[1], array[0]])
    else:
        return array

In [227]:
X[:2]

array([[0.08744127, 0.93810805],
       [0.06217424, 0.20944339]])

In [228]:
sort_2(X[:2])

[0.06217424 0.20944339]
<class 'numpy.ndarray'>


array([[0.06217424, 0.20944339],
       [0.08744127, 0.93810805]])

In [315]:
def sort_nest(array):
    
    length = len(array)
    
    if length == 2:
        if array[0][0] > array[1][0]:
            return np.array([array[1], array[0]])
        else:
            return array
    
    elif length > 2:
        array_l = array[:int(length/2)]
        array_r = array[int(length/2):]
        array_l_sorted = sort_nest(array_l)
        array_r_sorted = sort_nest(array_r)

        l = 0
        r = 0
        
        sorted_list = []
        
        for i in range(length):
            if r == int(length/2):
                sorted_list.append(array_l_sorted[l])
                l += 1

            elif l == int(length/2):
                sorted_list.append(array_r_sorted[r])
                r += 1             
                
            elif array_l_sorted[l][0] > array_r_sorted[r][0]:
                sorted_list.append(array_r_sorted[r])
                r += 1
                
            elif array_l_sorted[l][0] < array_r_sorted[r][0]:
                sorted_list.append(array_l_sorted[l])
                l += 1
        
        return np.array(sorted_list)

In [316]:
X = np.random.rand(64,2)

In [317]:
sort_nest(X)

array([[9.73321488e-04, 6.97422438e-02],
       [5.08735933e-03, 6.72939519e-01],
       [6.12907425e-03, 1.20175688e-01],
       [1.00879075e-02, 8.61235567e-01],
       [3.96344705e-02, 9.77594847e-03],
       [9.53001485e-02, 6.20508168e-01],
       [1.09777671e-01, 2.18689233e-01],
       [1.10248652e-01, 2.73417892e-01],
       [1.18893321e-01, 6.03165414e-01],
       [1.50303735e-01, 6.49919359e-01],
       [1.69950407e-01, 3.55541044e-02],
       [1.81519699e-01, 4.36286222e-01],
       [1.87160652e-01, 1.25236414e-01],
       [1.88402596e-01, 5.13827276e-01],
       [1.94947207e-01, 4.54964861e-01],
       [2.38413711e-01, 1.37414806e-01],
       [2.56350301e-01, 4.54730083e-01],
       [3.40608445e-01, 9.63513112e-02],
       [3.41266743e-01, 2.95481713e-01],
       [3.42491334e-01, 2.05732051e-01],
       [3.43048672e-01, 1.41941384e-01],
       [3.44723799e-01, 2.95388675e-01],
       [3.46899733e-01, 9.69932842e-01],
       [3.64187345e-01, 1.49832156e-01],
       [3.795622